[project]
name = "libsim"
version = "0.1.0"
description = "A python library simulator that dynamically generates modules on import."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litellm"
]
